!ArenaConfig 
arenas:
  0: !Arena
    pass_mark: 15
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: -1, y: 0, z: 5}
    - !Item
      name: SpawnerTree
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      spawnCounts: [10]
      finalValues: [2]
  1: !Arena
    pass_mark: 1
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: -1, y: 0, z: 5}
      rotations: [-1]
    - !Item
      name: GoodGoalMulti
      positions:
      - !Vector3 {x: -1, y: 0, z: 10}
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2}
  2: !Arena
    pass_mark: 1
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: -1, y: 0, z: 5}
      rotations: [-1]
    - !Item
      name: GoodGoalMulti
      positions:
      - !Vector3 {x: -1, y: 0, z: 20}
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2}