!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 1
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: -1, y: -1, z: -1}
      rotations: [-1]
    - !Item
      name: GoodGoalMulti
      positions:
      - !Vector3 {x: -1, y: -1, z: -1}
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2}
